name: Get Pods

on:
  push:
    branches: ["main"]

jobs:
  test:
    name: Get Pods in EKS
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      id-token: write
      contents: read
    steps:
    - name: EKS kubectl
      uses: ianbelcher/eks-kubectl-action@1.6
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: sa-east-1
        cluster_name: collider-qa
        # EKS role arn that allow access eks cluster (Mostly happen when you create your cluster with CDK).
        ##eks_role_arn: # optional
        # File to read and pass as stdin to kubectl
        ##stdin: # optional
        # The arguments that you want to pass through to the kubectl command
        args: get pods -A
