name: Get Pods

on:
  push:
    branches: ["main"]

jobs:
  test:
    name: Get Pods in EKS
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::653784090147:role/github-actions-oidc-Role-1EO4DNTXB38A
        role-session-name: GitHubActions
        audience: sts.amazonaws.com      
        aws-region: sa-east-1
    - name: Rollout restart deployment in EKS
      id: kubectl
      uses: ianbelcher/eks-kubectl-action@1.6
      with:
        cluster_name: collider-qa
        args: rollout restart deployment/${{ vars.DEPLOYMENT }} -n ${{ vars.KUBE_NAMESPACE }}
    - name: Output kubectl command
      run: echo "${{ steps.kubectl.outputs.kubectl-out }}"
