name: Get Pods

on:
  push:
    branches: ["main"]

jobs:
  test:
    name: Get Pods in EKS
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
    - name: EKS kubectl
      # You may pin to the exact commit or the version.
      # uses: ianbelcher/eks-kubectl-action@843a952573cab2e26f6ace831455592931b41a0c
      uses: ianbelcher/eks-kubectl-action@1.6
      with:
        # Your AWS_ACCESS_KEY_ID
        aws_access_key_id: secrets.AWS_ACCESS_KEY_ID
        # Your AWS_SECRET_ACCESS_KEY
        aws_secret_access_key: secrets.AWS_SECRET_ACCESS_KEY
        # The region of the cluster
        aws_region: sa-east-1
        # The name of the cluster you're using
        cluster_name: collider-qa
        # EKS role arn that allow access eks cluster (Mostly happen when you create your cluster with CDK).
        ##eks_role_arn: # optional
        # File to read and pass as stdin to kubectl
        ##stdin: # optional
        # The arguments that you want to pass through to the kubectl command
        args: get pods -A
